[[Xorg_xcb_util_wm]]
arch = "armv7l"
git-tree-sha1 = "e82590949a7ffd702a5395ff7e2493ac5affc232"
libc = "glibc"
os = "linux"

    [[Xorg_xcb_util_wm.download]]
    sha256 = "8f32cf8325f0cb625fccd43b6b3a31fe6249987555c53bab72f9470ab567a965"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_wm_jll.jl/releases/download/Xorg_xcb_util_wm-v0.4.1+0/Xorg_xcb_util_wm.v0.4.1.arm-linux-gnueabihf.tar.gz"
[[Xorg_xcb_util_wm]]
arch = "x86_64"
git-tree-sha1 = "409fe3416ce3e5bb1034cf9ec79473465a0644e6"
libc = "glibc"
os = "linux"

    [[Xorg_xcb_util_wm.download]]
    sha256 = "e3c30daa39d76f4dd1c13e1f6936e10cfd71fb433d9b890be9dfffc1818d5261"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_wm_jll.jl/releases/download/Xorg_xcb_util_wm-v0.4.1+0/Xorg_xcb_util_wm.v0.4.1.x86_64-linux-gnu.tar.gz"
[[Xorg_xcb_util_wm]]
arch = "aarch64"
git-tree-sha1 = "b632088360a7b501c7144a11033395dfdf834b04"
libc = "glibc"
os = "linux"

    [[Xorg_xcb_util_wm.download]]
    sha256 = "2904db3a518cc023111d0d4145c37bed7cb7cdb4ad4a36e8f563fd11ffd192aa"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_wm_jll.jl/releases/download/Xorg_xcb_util_wm-v0.4.1+0/Xorg_xcb_util_wm.v0.4.1.aarch64-linux-gnu.tar.gz"
[[Xorg_xcb_util_wm]]
arch = "i686"
git-tree-sha1 = "da3072beb96de721f3595e122895b8fe697bf03b"
libc = "musl"
os = "linux"

    [[Xorg_xcb_util_wm.download]]
    sha256 = "c57be179539f971149f6ee3794a69eed217cdda54fa79a3f6dc83d575f9d9f69"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_wm_jll.jl/releases/download/Xorg_xcb_util_wm-v0.4.1+0/Xorg_xcb_util_wm.v0.4.1.i686-linux-musl.tar.gz"
[[Xorg_xcb_util_wm]]
arch = "aarch64"
git-tree-sha1 = "abd2d189f91748e01731fbac1dedc297afb416d1"
libc = "musl"
os = "linux"

    [[Xorg_xcb_util_wm.download]]
    sha256 = "85df240dc205d576cf2e277588cdb30145d7e59700e72d4c6b72c860cb71fe5e"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_wm_jll.jl/releases/download/Xorg_xcb_util_wm-v0.4.1+0/Xorg_xcb_util_wm.v0.4.1.aarch64-linux-musl.tar.gz"
[[Xorg_xcb_util_wm]]
arch = "x86_64"
git-tree-sha1 = "e8ca820e6040042022eacabd2a960698466204cf"
os = "freebsd"

    [[Xorg_xcb_util_wm.download]]
    sha256 = "1834e79f5670b313d97f894d937f49a799f4995a1079b144d99ba2d456320f17"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_wm_jll.jl/releases/download/Xorg_xcb_util_wm-v0.4.1+0/Xorg_xcb_util_wm.v0.4.1.x86_64-unknown-freebsd11.1.tar.gz"
[[Xorg_xcb_util_wm]]
arch = "powerpc64le"
git-tree-sha1 = "286333cc13782e24bf6e989d7f06db402be91b32"
libc = "glibc"
os = "linux"

    [[Xorg_xcb_util_wm.download]]
    sha256 = "81d354206c79b26b418533f5dcf5fe33c015ba3d18bd7456e39ed3417c295b84"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_wm_jll.jl/releases/download/Xorg_xcb_util_wm-v0.4.1+0/Xorg_xcb_util_wm.v0.4.1.powerpc64le-linux-gnu.tar.gz"
[[Xorg_xcb_util_wm]]
arch = "i686"
git-tree-sha1 = "2c478368d83ecc98089831c22cfc24a9c46fc0d8"
libc = "glibc"
os = "linux"

    [[Xorg_xcb_util_wm.download]]
    sha256 = "fc55fde707dfcdad330e7276e736e4a816a99af92e96a2648e67b29ca06fc19e"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_wm_jll.jl/releases/download/Xorg_xcb_util_wm-v0.4.1+0/Xorg_xcb_util_wm.v0.4.1.i686-linux-gnu.tar.gz"
[[Xorg_xcb_util_wm]]
arch = "x86_64"
git-tree-sha1 = "1132baa7f4b1105debea49abb75dce36c559cd71"
libc = "musl"
os = "linux"

    [[Xorg_xcb_util_wm.download]]
    sha256 = "e15e73fd194d2e5cd6cf893daf2beca7cd183094e46db591e39ecad603aa1ba5"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_wm_jll.jl/releases/download/Xorg_xcb_util_wm-v0.4.1+0/Xorg_xcb_util_wm.v0.4.1.x86_64-linux-musl.tar.gz"
[[Xorg_xcb_util_wm]]
arch = "armv7l"
git-tree-sha1 = "8fdc58c3718b7f2cae1aeb820e1b4e948f9d49f1"
libc = "musl"
os = "linux"

    [[Xorg_xcb_util_wm.download]]
    sha256 = "c7a2c78a0dd3defd814cf9650cd82ae82a57bcb92f14a69e12856893c002f2d9"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_wm_jll.jl/releases/download/Xorg_xcb_util_wm-v0.4.1+0/Xorg_xcb_util_wm.v0.4.1.arm-linux-musleabihf.tar.gz"
